version: "3"

services:

  web-mvc:
    image: grpio/nerdstore-web-mvc-ecommerce:latest
    # container_name: nerdstore-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/SE.WebApp.MVC/Dockerfile
    # ports:
    #   - "5001:5001"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - dpkeys:/var/data_protection_keys/
    depends_on:
      - api-catalogo
      - api-identidade
      - api-cliente
      - api-bff-compras
  
  api-identidade:
    image: grpio/nerdstore-api-identidade:latest
    container_name: nerdstore-api-identidade
    build:
      context: ../src
      dockerfile: ./services/SE.Identidade.API/Dockerfile
    # ports:
    #   - "5101:5101"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5101

  api-carrinho:
    image: grpio/nerdstore-api-carrinho:latest
    container_name: nerdstore-api-carrinho
    build:
      context: ../src
      dockerfile: ./services/SE.Carrinho.API/Dockerfile
    # ports:
    #   - "5201:5201"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5201
    depends_on:
      - api-identidade

  api-catalogo:
    image: grpio/nerdstore-api-catalogo:latest
    container_name: nerdstore-api-catalogo
    build:
      context: ../src
      dockerfile: ./services/SE.Catalogo.API/Dockerfile
    # ports:
    #   - "5301:5301"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5301

  api-cliente:
    image: grpio/nerdstore-api-cliente:latest
    container_name: nerdstore-api-cliente
    build:
      context: ../src
      dockerfile: ./services/SE.Clientes.API/Dockerfile
    # ports:
    #   - "5401:5401"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5401
    depends_on:
      - api-identidade

  api-bff-compras:
    image: grpio/nerdstore-api-bff-compras:latest
    container_name: nerdstore-api-bff-compras
    build:
      context: ../src
      dockerfile: ./api gateways/SE.Bff.Compras/Dockerfile
    # ports:
    #   - "5501:5501"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5501
    depends_on:
      - api-identidade
      - api-carrinho
      - api-pagamento
      - api-pedido

  api-pagamento:
    image: grpio/nerdstore-api-pagamento:latest
    container_name: nerdstore-api-pagamento
    build:
      context: ../src
      dockerfile: ./services/SE.Pagamentos.API/Dockerfile
    # ports:
    #   - "5601:5601"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5601
    depends_on:
      - api-identidade
      - api-pedido

  api-pedido:
    image: grpio/nerdstore-api-pedido:latest
    container_name: nerdstore-api-pedido
    build:
      context: ../src
      dockerfile: ./services/SE.Pedidos.API/Dockerfile
    # ports:
    #   - "5701:5701"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5701
    depends_on:
      - api-identidade

  nerdstore-server:
    image: grpio/nerdstore-server:latest
    container_name: nerdstore-server
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-mvc

volumes:
  dpkeys: